"""Add Inquiry model and relationships

Revision ID: a0538771fe88
Revises: 
Create Date: 2025-04-09 06:14:29.528382

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a0538771fe88'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inquiry')
    with op.batch_alter_table('emails', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inquiry_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_emails_inquiry_id'), ['inquiry_id'], unique=False)
        batch_op.create_foreign_key(None, 'inquiries', ['inquiry_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emails', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_emails_inquiry_id'))
        batch_op.drop_column('inquiry_id')

    op.create_table('inquiry',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('date_received', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('dob', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('travel_start', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('travel_end', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('trip_cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('raw_email_content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='inquiry_pkey')
    )
    # ### end Alembic commands ###
